chore(test): accessibility violations (#5917)
I have another PR
[https://github.com/coveo/ui-kit/pull/5857](https://github.com/coveo/ui-kit/pull/5857)
that is blocked by a failing accessibility test on the merge queue. It’s
not failing locally or in the PR certifier, so I can't reproduce.

With the current assertions we can't see what the actual accessibility
issue are.
This changes the expect so we get the actual error messages.

Before:

```
Error: expect(received).toEqual(expected) // deep equality Expected: 0 Received: 1
```

After:

```
Error: expect(received).toEqual(expected) // deep equality

- Expected  -  1
+ Received  + 16

- Array []
+ Array [
+   Object {
+     "all": Array [],
+     "any": Array [],
+     "description": "This is a bogus violation for testing.",
+     "help": "Bogus violation help text.",
+     "helpUrl": "https://example.com/bogus-violation",
+     "id": "bogus-violation",
+     "impact": "minor",
+     "nodes": Array [],
+     "nodesData": Array [],
+     "none": Array [],
+     "tags": Array [],
+     "wcagTags": Array [],
+   },
+ ]
```

Please note that this violation was created by me for test purposes and
to highlight the difference in messaging.

This change will make any future accessibility errors more visible as
I've modified all the accessibility tests.